SELECT CH.FULL_NAME
FROM
	(SELECT EP_COUNT,
			CHARACTER_ID,
			MAX(EP_COUNT) OVER () AS MAX_EP
		FROM
			(SELECT COUNT(*) AS EP_COUNT,
					B.CHARACTER_ID
				FROM
					(SELECT A.CHARACTER_ID,
							EPISODE_ID
						FROM STOREFIRST.CHARACTERS_IN_EPISODES A
						JOIN STOREFIRST.CHARACTERS CH ON CH.CHARACTER_ID = A.CHARACTER_ID
						WHERE LAST_NAME != 'Smith'
							AND FULL_NAME != 'Rick Sanchez') B
				GROUP BY B.CHARACTER_ID) C) D
JOIN STOREFIRST.CHARACTERS CH ON CH.CHARACTER_ID = D.CHARACTER_ID
WHERE EP_COUNT = MAX_EP