SELECT NAME
FROM
	(SELECT COUNT(*),
			LOCATION_ID,
			MAX(COUNT(*)) OVER () AS MAX_COUNT
		FROM STOREFIRST.RESIDENTS_IN_LOCATIONS
		GROUP BY LOCATION_ID
		ORDER BY COUNT(*) DESC) A
JOIN STOREFIRST.LOCATIONS LOC ON A.LOCATION_ID = LOC.LOCATION_ID
WHERE COUNT = MAX_COUNT